config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :profile
    
  end
  
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'report', to: 'pages#report'
  get 'presentation', to: 'pages#presentation'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  resources :rescuers
  get 'user-heart-rate', to: 'pages#heart_rate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar,
                    :styles => {:medium => "300x300", :thumb => "100x100"},
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/rescuer.rb
class Rescuer < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
# GET request to /contact-us
  # Show new contact form
  def new
    @contact = Contact.new
  end

  # POST request to /contacts
  def create
    # Mass assignment of form fields into Contact object
    @contact = Contact.new(contact_params)
    # Save the contact object to database
    if @contact.save
      # store form fields via parameters, into variables
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      # Plug variables into Contact Mailer
      # email method and send email
      ContactMailer.contact_email(name, email, body).deliver
      # Store success message in flash hash
      # redirect to new action
      flash[:success] = "Thank you!"
      redirect_to new_contact_path
    else
      # if contact object doesn't save,
      # store error in flash hash,
      # and redirect_to the new action
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end

  private
  # collect data from form we need to use strong
  # parameters and whitelist the form fields
  def contact_params
    params.require(:contact).permit(:name, :email, :comments)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
  end
  
  def about
    
  end
  
  def report
    
  end
  
  def presentation
    
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!
  before_action :only_current_user
  # GET to /users/:user_id/profile/new
  def new
    # Render blank profile details form
    @profile = Profile.new
  end

  def create
    @user = User.find(params[:user_id])
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "Profile updated!"
      redirect_to root_path
    else
      render action: :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @profile = @user.profile
  end

  def update
    @user = User.find(params[:user_id])
    @profile = @user.profile
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile Updated!"
      redirect_to user_path(id: params[:user_id])
    else
      render action: :edit
    end
  end


  private
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :avatar, :age, :height_feet, :height_inches, :phone_number, :contact_email, :health_band)
  end

  def only_current_user
    @user = User.find(params[:user_id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/controllers/rescuers_controller.rb
class RescuersController < ApplicationController
  
  def new
    @rescuer = Rescuer.new
  end
  
  def create
    
    # Mass assignment of form fields into Rescuer object
    @rescuer = Rescuer.new(rescuer_params)
    
    # Save the contact object to database
    if @rescuer.save
      
      # store form fields via parameters, into variables
      name = params[:rescuer][:name]
      email = params[:rescuer][:email]
      phone = params[:rescuer][:phone]
      
      # Plug variables into Rescuer Mailer
      # email method and send email
      RescuerMailer.thankyou_email(name, email, phone).deliver
      
      # Store success message in flash hash
      # redirect to new action
      flash[:success] = "We will send you email confirmation. Thank you!"
      
      redirect_to root_path
    else
      # if contact object doesn't save,
      # store error in flash hash,
      # and redirect_to the new action
      flash[:danger] = @rescuer.errors.full_messages.join(", ")
      redirect_to new_rescuer_path
    end
  end
  
  private
  
  def rescuer_params
    params.require(:rescuer).permit(:name, :email, :phone, :location)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  # GET to /users/:id
  def show
    @user = User.find( params[:id] )
    @ref = Bigbertha::Ref.new( "https://rescuesenior-d31bf.firebaseio.com/" )
    #Enable this after you can inspect the data in firbase cloud database
    # @zone = Bigbertha::Ref.new( "https://rescuesenior-d31bf.firebaseio.com/heart_rate_zones" )
    @beacon = Bigbertha::Ref.new( "https://rescuesenior-d31bf.firebaseio.com/userBeacon/Beacons" )
    
    @beacon_location_1 = "Dinning Room [1st Floor Room 102]"
    @beacon_location_1_addrss = "Senior Citizen Living Condos, Upstate NYC 11103"
    
    @beacon_location_2 = "Bedroom [2nd Floor Room 20]"
    @beacon_location_2_addrss = "Senior Citizen Living Condos, Upstate NYC 11103"
    
    @beacon_location_3 = "Gymnasium [3rd Floor Room 311]"
    
    # @beacon_major = beacon.child(:major).val()
    # @beacon_minor = beacon.child(:minor).val()
    # if (@beacon_major == 16613 && @beacon_minor == 25364)
    
    # elsif (@beacon_major == 11480 && @beacon_minor == 44233)
    #   @beacon_location = "NAC room 7/207"
    # elsif (@beacon_major == 28803 && @beacon_minor == 64459)
    #   @beacon_location = "NAC room 7/208"
    # end
    # @beacon_accuracy = beacon.child(:accuracy).val()
    # @beacon_proximity = beacon.child(:proximity).val()
    # @beacon_rssi = beacon.child(:rssi).val()
    # @beacon_tx = beacon.child(:tx).val()
    # @beacon_uuid = beacon.child(:uuid).val()
    # redirect_to "http://localhost:3001"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/rescuers_helper.rb
module RescuersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def health_band_icon
    if @user.profile.health_band == "Fitbit"
      "<i class='fa fa-heartbeat'></i>".html_safe
    elsif @user.profile.health_band == "Apple Watch"
      "<i class='fa fa-lightbulb-o'></i>".html_safe
    elsif @user.profile.health_band == "Android Watch"
      "<i class='fa fa-dollar'></i>".html_safe
    end
  end
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Beta Sign-up</h3>
    <p class="text-center">Sign-up to receive email when we go live!</p>
    <div class="col-md-4 col-md-offset-4">
      <div class="well">
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: "form-control" %>
          </div>
          <%= f.submit 'Submit', class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueSenior</title>
  <%= csrf_meta_tags %>
  <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<body>
  <div id="wrap">
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a href="/" class="navbar-brand"><i class="fa fa-heartbeat"></i> RescueSeniors</a> -->
          <%= link_to root_path, class: "navbar-brand" do %>
          <i class="fa fa-heartbeat"></i>
          RescueSenior
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <!-- <li><a href="/about">About</a></li> -->
            <% if user_signed_in? %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
            <li><%= link_to "My Account", edit_user_registration_path %></li>
            <% else %>
            <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default navbar-btn" %>
            <% end %>
            
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <div class="flash-container flash-container">
      <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    
    <%= yield %>
  </div>
  <br class="clr" />
  
  <div id="footer">
    <div class="container">
      <div class="col-xs-12 col-sm-3">
        <b>Helpers</b>
        <br />
        <%= link_to 'Tips', '#' %>
        <br />
        <%= link_to 'Dashboard', '#' %>
      </div>
      <div class="col-xs-12 col-sm-3">
        <b>About</b>
        <br />
        <%= link_to 'Team', about_path %>
        <br />
        <%= link_to 'Project Report', report_path %>
        <br />
        <%= link_to 'Project Presentation', presentation_path %>
      </div>
      <div class="col-xs-12 col-sm-3">
        <b>Contact</b><br />
        <br />
        <%= link_to 'Contact-Us', new_contact_path, class: "btn btn-info btn-sm" %>
        
      </div>
      <div class="col-xs-12 col-sm-3 social">
        <b>Social</b>
        <br />
        <br />
        
        <%= link_to 'https://github.com/chaudhary27/Rescue-Senior-Web-App', target: "_blank" do %>
        <%= image_tag 'github.png', :class => 'social-button' %>
        <% end %>
        
        <%= link_to '#', target: "_blank" do %>
        <%= image_tag 'facebook.png', :class => 'social-button' %>
        <% end %>
        
        <%= link_to '#', target: "_blank" do %>
        <%= image_tag 'twitter.png', :class => 'social-button' %>
        <% end %>
        
      </div>
    </div>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<!-- <div class="container text-center">
<h1>About Us</h1>
<p>We are a team of students building location aware health emergency solutions for senior citizens.
Our academic mentors are Professor Xiao, Professor Zhu, and Professor Baurin.</p>
<p>We are utilizing Estimote proximity beacons to collect accurate location data
and Fitbit health tracking band to collect
health data. Our goal is to analyze health data such as heart rate for any abnormal signs and
proactively suggest senior citizens to take action. Our system will dispatch help in
case of emergency with health report and accurate location data.</p>
</div> -->

<div class="container">
  <!-- Introduction Row -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">About Us
        <!-- <small>It's Nice to Meet You!</small> -->
      </h1>
      <h4>We are a team of students building location aware health emergency solutions for senior citizens.</h4>
    </div>
  </div>
  
  <!-- Team Members Row -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">Our Team</h2>
    </div>
    <div class="col-lg-4 col-sm-6">
      <%= link_to 'https://www.linkedin.com/in/farooqfaisal/', target: '_blank' do %>
      <img class="img-circle img-responsive img-center" src="http://i.imgur.com/p26ttVE.jpg" alt="">
      <% end %>
      <h3>Faisal Farooq
        <small>Electrical Engineering</small>
      </h3>
      <!-- <%= link_to '#', target: "_blank" do %>
      <%= image_tag 'linkedin.png', :class => 'social-button' %>
      <% end %> -->
    </div>
    <div class="col-lg-4 col-sm-6">
      <%= link_to 'https://www.linkedin.com/in/stephen-oakey-51904561/', target: '_blank' do %>
      <img class="img-circle img-responsive img-center" src="http://i.imgur.com/WatWxcp.jpg" alt="">
      <% end %>
      <h3>Stephen Oakey
        <small>Electrical Engineering</small>
      </h3>
      <!-- <p>What does this team member to? Keep it short! This is also a great spot for social links!</p> -->
    </div>
    <div class="col-lg-4 col-sm-6">
      <%= link_to 'https://www.linkedin.com/in/aaron-almonte-seiffe-2230755a/', target: '_blank' do %>
      <img class="img-circle img-responsive img-center" src="http://i.imgur.com/0YKoN11.jpg" alt="">
      <% end %>
      <h3>Aaron Almonte
        <small>Electrical Engineering</small>
      </h3>
      <!-- <p>What does this team member to? Keep it short! This is also a great spot for social links!</p> -->
    </div>
    <div class="col-lg-4 col-sm-6">
      <%= link_to 'https://www.linkedin.com/in/md-rahman-59b8a411a/', target: '_blank' do %>
      <img class="img-circle img-responsive img-center" src="http://i.imgur.com/JtEVdMr.jpg" alt="">
      <% end %>
      <h3>Mostafiz Rahman
        <small>Electrical Engineering</small>
      </h3>
      <!-- <p>What does this team member to? Keep it short! This is also a great spot for social links!</p> -->
    </div>
    <div class="col-lg-12">
      <h2 class="page-header">Academic Mentors</h2>
    </div>
    <div class="col-lg-4 col-sm-6">
      <%= link_to 'https://www.linkedin.com/in/jizhong-xiao-9a041b5/', target: '_blank' do %>
      <img class="img-circle img-responsive img-center" src="http://i.imgur.com/q1nuooH.jpg" alt="">
      <% end %>
      <h3>Professor Xiao
        <small>EE Dept. CCNY</small>
      </h3>
      <!-- <p>What does this team member to? Keep it short! This is also a great spot for social links!</p> -->
    </div>
    <div class="col-lg-4 col-sm-6">
      <%= link_to 'http://www-cs.ccny.cuny.edu/~zhu/', target: '_blank' do %>
      <img class="img-circle img-responsive img-center" src="http://i.imgur.com/idkIMqD.jpg" alt="">
      <% end %>
      <h3>Professor Zhu
        <small>CS Dept. CCNY</small>
      </h3>
      <!-- <p>What does this team member to? Keep it short! This is also a great spot for social links!</p> -->
    </div>
    <div class="col-lg-4 col-sm-6">
      <%= link_to 'https://www.linkedin.com/in/bingoo/', target: '_blank' do %>
      <img class="img-circle img-responsive img-center" src="http://i.imgur.com/yT5IlDY.jpg" alt="">
      <% end %>
      <h3>Bing Li
        <small>PhD Candidate CCNY</small>
      </h3>
      <!-- <p>What does this team member to? Keep it short! This is also a great spot for social links!</p> -->
    </div>
  </div>
  
</div>
<!-- /.container -->

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <h1>Welcome to RescueSenior</h1>
  <h3>We are a team of students building location aware health emergency solutions for senior citizens.</h3>
</div>
<div class="container home-signup-links">
  <div class="row">
    <% if user_signed_in? %>
    <div class="col-md-6">
      <div class="well">
        <div class="text-center">
          <h2 class="text-center">Connect your health tracking device</h2>
          <% if current_user.profile %>
          <%= link_to "Edit your profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
          <%= link_to "View your profile", user_path(current_user.id), class: 'btn btn-default btn-lg btn-block' %>
          <% else %>
          <p>Create your profile to connect health device.</p>
          <%= link_to "Create profile and enable health tracking", new_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">
          Enable Location Tracking
        </h2>
        <p>Download our app. This will allow us to send help in case of emergency.</p>
        <%= link_to "Enable Beacon Location", 'https://creator.ionic.io/share/9be786b005a0', class: 'btn btn-default btn-lg btn-block', target: '_blank' %>
      </div>
    </div>
    <% else %>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Connect Health Tracking</h2>
        <h4 class="text-center">Sign up and create a profile to get started.</h4>
        <br>
        <%= link_to "Sign up & create a profile", new_user_registration_path, class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Enable Location Beacon</h2>
        <h4 class="text-center">This will help us send help in case of emergency.</h4>
        <br>
        <%= link_to "Download app to allow tracking via beacon", 'https://creator.ionic.io/share/9be786b005a0', class: 'btn btn-success btn-lg btn-block', target: '_blank' %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div id="feature">
  <div class="container">
    <div class="row">
      <div class="text-center">
        <h3>Rescue Senior Intro Video</h3>
      </div>
      <p align="center"><iframe width="760" height="510" src="https://www.youtube.com/embed/SJVc9ZQ4wdY" frameborder="0" allowfullscreen></iframe></p>
    </div>
  </div>
</div>

<div id="feature">
  <div class="container">
    <div class="row">
      <div class="text-center">
        <h3>How it works</h3>
        <p>Our system provides an end-to-end health monitring and tracking for senior citizens.</p>
      </div>
      <div class="col-md-3 wow fadeInRight" data-wow-offset="0" data-wow-delay="0.3s">
        <div class="text-center">
          <div class="hi-icon-wrap hi-icon-effect">
            <i class="fa fa-laptop"></i>
            <h2>Profile</h2>
            <p>Make an account and provide some profile details.</p>
          </div>
        </div>
      </div>
      <div class="col-md-3 wow fadeInRight" data-wow-offset="0" data-wow-delay="0.3s">
        <div class="text-center">
          <div class="hi-icon-wrap hi-icon-effect">
            <i class="fa fa-heart-o"></i>
            <h2>Health Tracking</h2>
            <p>Integrate health fitness device to allow health monitoring.</p>
          </div>
        </div>
      </div>
      <div class="col-md-3 wow fadeInLeft" data-wow-offset="0" data-wow-delay="0.3s">
        <div class="text-center">
          <div class="hi-icon-wrap hi-icon-effect">
            <i class="fa fa-database"></i>
            <h2>Health Analytics</h2>
            <p>We process your health data to monitor your vitals.</p>
          </div>
        </div>
      </div>
      <div class="col-md-3 wow fadeInLeft" data-wow-offset="0" data-wow-delay="0.3s">
        <div class="text-center">
          <div class="hi-icon-wrap hi-icon-effect">
            <i class="fa fa-medkit"></i>
            <h2>Emergency Help</h2>
            <p>In case of emergency we send help to you.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Banner Download -->
<div class="banner">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center wrap_title">
        <h2>Subscribe to be a Rescuer</h2>
        <p class="lead" style="margin-top:0"></p>
        <!--<p><a class="btn btn-embossed btn-primary view" role="button">Sign up now</a></p>-->
        <p><%= link_to "Sign up now", new_rescuer_path, class: 'btn btn-embossed btn-primary view' %></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/presentation.html.erb
<p align="center">
  <iframe src="https://docs.google.com/presentation/d/1JhxCDd3wwpNZsEonUmak68k7tSh2sFxq03CQNiO0SuQ/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
</p>

app/views/pages/report.html.erb
<p align="center">
  <iframe src="https://drive.google.com/file/d/0B4VfQZaFPuPVV2hrdUZVRzg2SGM/preview" width="640" height="800">
  </iframe></p>
  

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => {:multipart => true} do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :age %>
    <%= f.text_field :age, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :height_feet %>
    <%= f.text_field :height_feet, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :height_inches %>
    <%= f.text_field :height_inches, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :health_band %>
    <!-- <%= f.text_field :health_band, class: 'form-control' %> -->
    <%= f.select :health_band, ['Fitbit', 'Apple Watch', 'Android Watch'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Edit your profile</h1>
      <p class="text-center">Creare profile and authenticate health band</p>
      <div class="well">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/rescuers/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Become a rescuer</h3>
    <p class="text-center">Help senior citizens in case of an emergency</p>
    <div class="col-md-4 col-md-offset-4">
      <div class="well">
        <%= form_for @rescuer do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "Alex Gale" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control", placeholder: "gale@example.com"%>
        </div>
        <div class="form-group">
          <%= f.label :phone %>
          <%= f.text_field :phone, class: "form-control", placeholder: "555-555-5555" %>
        </div>
        <div class="form-group">
          <%= f.label :location %>
          <%= f.text_field :location, class: "form-control", placeholder: "City, State" %>
        </div>
        <%= f.submit 'Submit', class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>